# Objetivo

Has sido contratado(a) como Analista de Datos por una cadena de tiendas de bebidas y deberás crear análisis sobre el negocio utilizando una base de datos en un archivo Excel, que fue extraída del sistema de ventas de la cadena.

Para esto vamos a utilizar las librerías pandas, openpyxl, plotly nbformat

In [ ]:
%pip install pandas
%pip install openpyxl
%pip install plotly nbformat

In [4]:
import pandas as pd

data = pd.read_excel('BD Ventas.xlsx')
data.head() # Imprime las primeras 5 filas del DataFrame (Libro de Excel).

,Region,Fecha,Tienda,Ciudad,País,Tamaño,Local_Consumo,Precio,Forma_Pago
0,PED1994,2022-01-01,Tienda 4,Guadalajara,México,300ml,Consumo en tienda,5,Efectivo
1,PED2246,2022-01-01,Tienda 6,Santiago de Chile,Chile,500ml,Consumo en tienda,11,Débito
2,PED3876,2022-01-01,Tienda 3,Bogotá,Colombia,300ml,Delivery,7,Crédito
3,PED4352,2022-01-01,Tienda 1,Buenos Aires,Argentina,1000ml,Consumo en tienda,7,Débito
4,PED8633,2022-01-01,Tienda 5,Ciudad de México,México,200ml,Delivery,9,Crédito

In [5]:
data.tail() # Imprime las últimas 5 filas del DataFrame (Libro de Excel).

,Region,Fecha,Tienda,Ciudad,País,Tamaño,Local_Consumo,Precio,Forma_Pago
69995,PED67084,2024-12-31,Tienda 6,Santiago de Chile,Chile,500ml,Consumo en tienda,11,Crédito
69996,PED67857,2024-12-31,Tienda 3,Bogotá,Colombia,200ml,Consumo en tienda,7,Nequi
69997,PED69171,2024-12-31,Tienda 4,Guadalajara,México,500ml,Consumo en tienda,5,Efectivo
69998,PED69229,2024-12-31,Tienda 4,Guadalajara,México,300ml,Consumo en tienda,9,Nequi
69999,PED69356,2024-12-31,Tienda 1,Buenos Aires,Argentina,300ml,Delivery,9,Nequi

In [7]:
data.shape # Imprime el número de filas y columnas del DataFrame (Libro de Excel).

(70000, 9)

In [8]:
data.info() # Muestra información general sobre el DataFrame, incluyendo el número de filas, columnas, tipos de datos y valores nulos.

<class 'pandas.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Region         70000 non-null  str
 1   Fecha          70000 non-null  datetime64[us]
 2   Tienda         70000 non-null  str
 3   Ciudad         70000 non-null  str
 4   País           70000 non-null  str
 5   Tamaño         70000 non-null  str
 6   Local_Consumo  70000 non-null  str
 7   Precio         70000 non-null  int64
 8   Forma_Pago     70000 non-null  str
dtypes: datetime64[us](1), int64(1), str(7)
memory usage: 4.8 MB

In [15]:
data['Precio'].describe() # Proporciona estadísticas descriptivas para la columna 'Precio'.

count    70000.000000
mean         8.355200
std          2.653061
min          5.000000
25%          7.000000
50%          7.000000
75%         11.000000
max         13.000000
Name: Precio, dtype: float64

In [17]:
data['Tienda'].unique() # Muestra los valores únicos en la columna 'tienda'.

<StringArray>
['Tienda 4', 'Tienda 6', 'Tienda 3', 'Tienda 1', 'Tienda 5', 'Tienda 2']
Length: 6, dtype: str

In [18]:
data['Tienda'].value_counts() # Cuenta la frecuencia de cada valor único en la columna 'Tienda'. La cantidad de veces que se repite cada valor único.

Tienda
Tienda 4    13483
Tienda 6    13075
Tienda 1    12344
Tienda 5    12177
Tienda 3    10603
Tienda 2     8318
Name: count, dtype: int64

# groupby()
## Agrupando datos

El método groupby() realiza el agrupamiento de datos por una determinada columna. Siempre que utilizamos este método, necesitamos definir la función de agregación que se aplicará a los datos. Ejemplo: sum() para suma y mean() para promedio.

Para este caso vamos a decirle que agrupe por 'Tienda' y que calcule suma por el criterio 'Precio'

In [19]:
data.groupby('Tienda')['Precio'].sum() # Agrupa los datos por la columna 'Tienda' y calcula el precio total para cada tienda.

Tienda
Tienda 1    103162
Tienda 2     69592
Tienda 3     88357
Tienda 4    112379
Tienda 5    102189
Tienda 6    109185
Name: Precio, dtype: int64